version: '3.4'

services:
  apitodocker:
    depends_on:
        - mssql
    image: apitodocker
    container_name: api
    build:
      context: APIToDocker/
      dockerfile: Dockerfile
    links:
      - mssql
    ports:
      - "3101:3100"



  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - "1434:1433"
    volumes:
      - "mssql_db_data:/var/opt/mssql:Z"

volumes:
    mssql_db_data: